### ISSUE TITLE
Freehold question

### ISSUE THREAD

**Issue by nickbe** [timshannon/freehold#1]
Hi Tim,

Is freehold still working? Any reasons against using it from your point of view?
Thanks in advance
Nick

**Comment by timshannon** [comment]
I haven't  touched it in a few years, but there's no reason it shouldn't work.  If you have any issues getting it up and running, feel free to ping me.

**Comment by nickbe** [comment]
Hi Tim,

thanks for getting back to me so soon 😄 

Getting up and running was never a problem, but should there be any other issue I'd be more than happy to know that you're still around 😀 

We've tested several programs today, looking at only a few options in the end. While seafile is one of them, freehold is a jewel on its own due to its simplicity.

I myself am still using freehold for many years now without thinking that you might have stopped developing it. Well, we tend to forget about things which just work.
